version: "3.8"

services:
  user-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://postgres:mostwanted3z@db:5432/userdb
    depends_on:
      - db
    networks:
      - shared-network  # <-- Add this line to use the same network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mostwanted3z
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network  # <-- Add this line to use the same network

networks:
  shared-network:  # <-- Add this to connect with booking-service
    name: shared-network
    driver: bridge

volumes:
  postgres_data:
